# Generated by Django 3.2 on 2021-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=40)),
                ('From', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
